# Generated by Django 5.2.16 on 2026-07-29 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0008_animalphoto_collection_collectionmember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('inheritance_type', models.CharField(choices=[('DOMINANT', 'Домinant'), ('RECESSIVE', 'Рецессивный'), ('CODOMINANT', 'Кодominant')], max_length=20)),
            ],
            options={
                'verbose_name': 'Ген',
                'verbose_name_plural': 'Гены',
            },
        ),
        migrations.CreateModel(
            name='MorphGene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genotype', models.CharField(choices=[('HET', 'Гетero'), ('HOM', 'Гомо'), ('SUPER', 'Super')], default='HET', max_length=10)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genetics.gene')),
                ('morph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genes', to='animals.morph')),
            ],
            options={
                'unique_together': {('morph', 'gene')},
            },
        ),
    ]
