# Generated by Django 5.2 on 2025-04-12 12:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-acquisition_date'], 'verbose_name': 'Животное', 'verbose_name_plural': 'Животные'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name': 'Вид', 'verbose_name_plural': 'Виды'},
        ),
        migrations.AddField(
            model_name='animal',
            name='acquisition_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата приобретения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, upload_to='animals/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения/вылупления'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.species', verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название вида'),
        ),
    ]
