# Generated by Django 5.2 on 2025-04-14 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_alter_animal_options_alter_species_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Morph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название морфы"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Морфа",
                "verbose_name_plural": "Морфы",
            },
        ),
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Класс"),
                ),
                (
                    "order",
                    models.CharField(blank=True, max_length=100, verbose_name="Отряд"),
                ),
                (
                    "family",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Семейство"
                    ),
                ),
                (
                    "genus",
                    models.CharField(blank=True, max_length=100, verbose_name="Род"),
                ),
                (
                    "species",
                    models.CharField(max_length=100, unique=True, verbose_name="Вид"),
                ),
                (
                    "subspecies",
                    models.CharField(blank=True, max_length=100, verbose_name="Подвид"),
                ),
                (
                    "scientific_name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Научное название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Таксон",
                "verbose_name_plural": "Таксоны",
            },
        ),
        migrations.RemoveField(
            model_name="animal",
            name="species",
        ),
        migrations.AddField(
            model_name="animal",
            name="care_level",
            field=models.CharField(
                choices=[
                    ("BEGINNER", "Новичок"),
                    ("INTERMEDIATE", "Средний"),
                    ("EXPERT", "Эксперт"),
                ],
                default=0,
                max_length=20,
                verbose_name="Сложность ухода",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="animal",
            name="habitat",
            field=models.CharField(
                choices=[
                    ("TROPICAL", "Тропическая"),
                    ("DESERT", "Пустынная"),
                    ("AQUATIC", "Полуводная"),
                ],
                default=0,
                max_length=20,
                verbose_name="Среда обитания",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("FEEDING", "Кормление"),
                            ("CLEANING", "Уборка"),
                            ("TREATMENT", "Лечение"),
                            ("BREEDING", "Размножение"),
                            ("OBSERVATION", "Наблюдение"),
                            ("OTHER", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Тип действия",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата и время"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="animals.animal",
                        verbose_name="Животное",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Действие",
                "verbose_name_plural": "Действия",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="animal",
            name="morph",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="animals.morph",
                verbose_name="Морфа",
            ),
        ),
        migrations.AddField(
            model_name="morph",
            name="taxonomy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="animals.taxonomy",
                verbose_name="Таксон",
            ),
        ),
        migrations.CreateModel(
            name="CareRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temperature_min",
                    models.FloatField(verbose_name="Минимальная температура (°C)"),
                ),
                (
                    "temperature_max",
                    models.FloatField(verbose_name="Максимальная температура (°C)"),
                ),
                (
                    "humidity_min",
                    models.FloatField(verbose_name="Минимальная влажность (%)"),
                ),
                (
                    "humidity_max",
                    models.FloatField(verbose_name="Максимальная влажность (%)"),
                ),
                ("diet", models.TextField(verbose_name="Рацион")),
                ("lighting", models.TextField(blank=True, verbose_name="Освещение")),
                ("substrate", models.TextField(blank=True, verbose_name="Субстрат")),
                (
                    "taxonomy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="animals.taxonomy",
                        verbose_name="Таксон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Требование по уходу",
                "verbose_name_plural": "Требования по уходу",
            },
        ),
        migrations.AddField(
            model_name="animal",
            name="taxonomy",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="animals.taxonomy",
                verbose_name="Таксон",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="morph",
            unique_together={("taxonomy", "name")},
        ),
    ]
