# Generated by Django 5.2 on 2025-04-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0003_morph_taxonomy_remove_animal_species_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="cost",
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
