# Generated by Django 5.2 on 2025-04-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0005_alter_action_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Затраты"
            ),
        ),
    ]
