# Generated by Django 5.2.16 on 2026-07-29 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_alter_action_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='acquisition_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата приобретения'),
        ),
    ]
