# Generated by Django 5.2 on 2025-04-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0006_alter_action_cost"),
        ("feeding", "0002_fooditem_feedingschedule_feedingevent_delete_feeding"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxonomy",
            name="allowed_foods",
            field=models.ManyToManyField(
                related_name="taxonomies", to="feeding.fooditem"
            ),
        ),
    ]
