# Generated by Django 5.2.16 on 2026-07-29 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_alter_acquisition_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animals/gallery/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Фото животного',
                'verbose_name_plural': 'Фото животных',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_global', models.BooleanField(default=False, verbose_name='Общая библиотека')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='CollectionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Просмотр'), ('editor', 'Редактор')], default='viewer', max_length=20)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='animals.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('collection', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.AddField(
            model_name='animal',
            name='parent_f',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_f', to='animals.animal', verbose_name='Мать'),
        ),
        migrations.AddField(
            model_name='animal',
            name='parent_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_m', to='animals.animal', verbose_name='Отец'),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='is_global',
            field=models.BooleanField(default=True, verbose_name='Глобальный справочник'),
        ),
        migrations.AddField(
            model_name='animalphoto',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='animals.animal', verbose_name='Животное'),
        ),
        migrations.AddField(
            model_name='animal',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='animals.collection', verbose_name='Коллекция'),
        ),
    ]
