# Generated by Django 6.0.7 on 2026-07-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_animalphoto_collection_collectionmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='common_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Народное название'),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='library_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID в справочнике'),
        ),
    ]
