# Generated by Django 6.0.7 on 2026-07-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_taxonomy_library_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='carerequirement',
            name='catalog_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Расширенные детали справочника'),
        ),
    ]
