# Generated by Django 6.0.7 on 2026-07-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_care_catalog_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичная ссылка'),
        ),
        migrations.AddField(
            model_name='collection',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Публичный токен'),
        ),
    ]
