# Generated by Django 6.0.7 on 2026-07-29 15:41

import animals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0011_backlog_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalphoto',
            name='image',
            field=models.ImageField(upload_to=animals.models.animal_gallery_upload_to, verbose_name='Фото'),
        ),
    ]
