# Generated by Django 6.0.7 on 2026-07-29 14:05

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.ApprovedUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='User finished the first-run wizard.', verbose_name='Onboarding completed'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Linked Telegram chat for reminders.', max_length=64, verbose_name='Telegram chat id'),
        ),
    ]
