# Generated by Django 5.2.16 on 2026-07-29 08:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0008_animalphoto_collection_collectionmember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата начала')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('female', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_as_female', to='animals.animal', verbose_name='Самка')),
                ('male', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_as_male', to='animals.animal', verbose_name='Самец')),
            ],
            options={
                'verbose_name': 'Пара для разведения',
                'verbose_name_plural': 'Пары для разведения',
            },
        ),
        migrations.CreateModel(
            name='Clutch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lay_date', models.DateField(verbose_name='Дата кладки')),
                ('egg_count', models.PositiveIntegerField(verbose_name='Кол-во яиц')),
                ('infertile_count', models.PositiveIntegerField(default=0, verbose_name='Нefertil')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clutches', to='incubation.breedingpair')),
            ],
            options={
                'verbose_name': 'Кладка',
                'verbose_name_plural': 'Кладки',
            },
        ),
        migrations.CreateModel(
            name='IncubationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало инкубации')),
                ('expected_hatch', models.DateField(verbose_name='Ожидаемое вылупление')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Температура °C')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='Влажность %')),
                ('clutch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incubation', to='incubation.clutch')),
            ],
            options={
                'verbose_name': 'Инкубация',
                'verbose_name_plural': 'Инкубации',
            },
        ),
        migrations.CreateModel(
            name='HatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatch_date', models.DateField(verbose_name='Дата вылупления')),
                ('hatched_count', models.PositiveIntegerField(verbose_name='Вылупилось')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('incubation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hatches', to='incubation.incubationrecord')),
            ],
            options={
                'verbose_name': 'Запись вылупления',
                'verbose_name_plural': 'Записи вылупления',
            },
        ),
    ]
