# Generated by Django 5.2.16 on 2026-07-29 08:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_animalphoto_collection_collectionmember_and_more'),
        ('feeding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата кормления')),
                ('food_type', models.CharField(max_length=100, verbose_name='Тип корма')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('action', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_log', to='animals.action')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_logs', to='animals.animal', verbose_name='Животное')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Запись кормления',
                'verbose_name_plural': 'Записи кормления',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FeedingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_days', models.PositiveIntegerField(default=7, verbose_name='Интервал (дней)')),
                ('food_type', models.CharField(max_length=100, verbose_name='Тип корма')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('last_fed', models.DateTimeField(blank=True, null=True, verbose_name='Последнее кормление')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_schedule', to='animals.animal', verbose_name='Животное')),
            ],
            options={
                'verbose_name': 'Расписание кормления',
                'verbose_name_plural': 'Расписания кормления',
            },
        ),
        migrations.DeleteModel(
            name='Feeding',
        ),
    ]
