# Generated by Django 5.2 on 2025-04-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0007_taxonomy_allowed_foods"),
        ("feeding", "0002_fooditem_feedingschedule_feedingevent_delete_feeding"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedingevent",
            name="used_calcium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feedingevent",
            name="used_multivitamins",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feedingevent",
            name="used_vitamin_d3",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="requires_calcium",
            field=models.CharField(
                choices=[
                    ("daily", "Ежедневно"),
                    ("every_feeding", "Каждое кормление"),
                    ("weekly", "Еженедельно"),
                    ("biweekly", "Раз в 2 недели"),
                    ("none", "Не требуется"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="requires_multivitamins",
            field=models.CharField(
                choices=[
                    ("daily", "Ежедневно"),
                    ("every_feeding", "Каждое кормление"),
                    ("weekly", "Еженедельно"),
                    ("biweekly", "Раз в 2 недели"),
                    ("none", "Не требуется"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="requires_vitamin_d3",
            field=models.CharField(
                choices=[
                    ("daily", "Ежедневно"),
                    ("every_feeding", "Каждое кормление"),
                    ("weekly", "Еженедельно"),
                    ("biweekly", "Раз в 2 недели"),
                    ("none", "Не требуется"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FeedingRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("newborn", "Новорождённый (0–6 месяцев)"),
                            ("juvenile", "Ювенильный (6–18 месяцев)"),
                            ("adult", "Взрослый (18+ месяцев)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "food_type",
                    models.CharField(
                        choices=[
                            ("insect", "Насекомые"),
                            ("plant", "Растения"),
                            ("rodent", "Грызуны"),
                            ("mixed", "Смешанный"),
                        ],
                        max_length=20,
                    ),
                ),
                ("insect_ratio", models.IntegerField(default=0)),
                ("plant_ratio", models.IntegerField(default=0)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневно"),
                            ("every_other_day", "Через день"),
                            ("every_3_days", "Каждые 3 дня"),
                            ("weekly", "Еженедельно"),
                            ("biweekly", "Раз в 2 недели"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity_per_feeding", models.IntegerField()),
                (
                    "calcium_frequency",
                    models.CharField(
                        choices=[
                            ("every_feeding", "Каждое кормление"),
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("biweekly", "Раз в 2 недели"),
                            ("none", "Не требуется"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "vitamin_d3_frequency",
                    models.CharField(
                        choices=[
                            ("every_feeding", "Каждое кормление"),
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("biweekly", "Раз в 2 недели"),
                            ("none", "Не требуется"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "multivitamin_frequency",
                    models.CharField(
                        choices=[
                            ("every_feeding", "Каждое кормление"),
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("biweekly", "Раз в 2 недели"),
                            ("none", "Не требуется"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "taxonomy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feeding_requirements",
                        to="animals.taxonomy",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feedingevent",
            name="requirement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feeding.feedingrequirement",
            ),
        ),
    ]
