# Generated by Django 5.2.16 on 2026-07-29 08:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0008_animalphoto_collection_collectionmember_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('reason', models.CharField(max_length=200, verbose_name='Причина')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Диагноз')),
                ('treatment', models.TextField(blank=True, verbose_name='Лечение')),
                ('vet_name', models.CharField(blank=True, max_length=100, verbose_name='Ветеринар')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Затраты')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='Следующий визит')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='animals.animal', verbose_name='Животное')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Медицинская запись',
                'verbose_name_plural': 'Медицинские записи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SheddingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('quality', models.CharField(choices=[('COMPLETE', 'Полная'), ('PARTIAL', 'Частичная'), ('PROBLEMS', 'Проблемы')], default='COMPLETE', max_length=20, verbose_name='Качество')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shedding_logs', to='animals.animal', verbose_name='Животное')),
            ],
            options={
                'verbose_name': 'Линька',
                'verbose_name_plural': 'Линьки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('weight_g', models.FloatField(verbose_name='Вес (г)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='animals.animal', verbose_name='Животное')),
            ],
            options={
                'verbose_name': 'Запись веса',
                'verbose_name_plural': 'Записи веса',
                'ordering': ['-date'],
            },
        ),
    ]
